### ISSUE TITLE
Question about the reliability of the data

### ISSUE THREAD

**Issue by Jejugo** [mariotaddeucci/b3api#2]
Hello Mario! I appreciate your effort to take the time and create this great package for us!

Would you mind sharing how you were able to access this information for B3? I am building a dashboard for a client and would like to know how reliable this information is. Also, I am thinking about adding some improvements/endpoints so we have other information like company sectors, profits, growth, etc

**Comment by mariotaddeucci** [comment]
Hey @Jejugo, the information comes from google finance api. For B3, some assets can take 15 minutes to be updated.
All "ETFs de Renda Fixa" are not available because it's not supported on google finance api.
To maintain this API up, I'm using the Vercel free tier service.
